### ISSUE TITLE
How do I produce the  file loop.out 

### ISSUE THREAD

**Issue by Grople** [Saumya-Gupta-26/struct-uncertainty#3]
Hello, I tried to use your code, but I find a question.  The code loop.out is not given. look forward to your answer!

**Comment by Saumya-Gupta-26** [comment]
Hi, it's here : https://github.com/Saumya-Gupta-26/struct-uncertainty/blob/main/src/loop.out

**Comment by Saumya-Gupta-26** [comment]
Hi, it's here : https://github.com/Saumya-Gupta-26/struct-uncertainty/blob/main/src/loop.out

**Comment by Grople** [comment]
thanks for your answer, I  do need a source code of loop.out,  not a binary file.

**Comment by Saumya-Gupta-26** [comment]
Hi, the code runs correctly using the loop.out binary file. Is there a reason you need the source code instead?

**Comment by Grople** [comment]
Yes, I need the source code for better know your paper, there some details comfused me.

**Comment by Saumya-Gupta-26** [comment]
I see. I have uploaded it here : https://github.com/Saumya-Gupta-26/struct-uncertainty/blob/main/src/loop.cpp

**Comment by Grople** [comment]
thanks for your help. Your paper is great, I studied for several days!
